title = "Hue Vietnamese Cuisine"
# logo = "URL to logo"
base_url = "http://localhost:3000"
about = ""
index_site_pages = ["blog"]

[extra]
copyright = "Dang Van Thanh"
github = "https://github.com/dangvanthanh"
twitter = "https://twitter.com/dangvanthanh"
hobby = "Food Lover"

date_style = "%B %e, %Y"
